project_id = "codex"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/dashboard"]
jwt_expiry = 3600
enable_signup = true
minimum_password_length = 8

enable_email_signup = true
enable_email_signin = true
enable_phone_signup = false
enable_phone_signin = false

test_mode = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.external.google]
enabled = true
client_id = "{{ .Env.GOOGLE_CLIENT_ID }}"
secret = "{{ .Env.GOOGLE_CLIENT_SECRET }}"
redirect_uri = "{{ .Env.GOOGLE_REDIRECT_URI | default \"http://localhost:3000/auth/callback\" }}"

[auth.external.apple]
enabled = true
client_id = "{{ .Env.APPLE_CLIENT_ID }}"
secret = "{{ .Env.APPLE_CLIENT_SECRET }}"
redirect_uri = "{{ .Env.APPLE_REDIRECT_URI | default \"http://localhost:3000/auth/callback\" }}"
