name: Build and deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Save production bundle
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Upload to HostGator public_html
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.HOSTGATOR_FTP_HOST }}
          username: ${{ secrets.HOSTGATOR_FTP_USER }}
          password: ${{ secrets.HOSTGATOR_FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: dist/
          server-dir: public_html/
          state-name: .ftp-deploy-sync-state.json
